In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11493376/11490434 [==============================] - 105s 9us/step


In [3]:
import matplotlib.pyplot as plt
plt.imshow(x_train[0])

In [4]:
x_train[0].shape

(28, 28)

In [6]:
x_train = x_train.reshape(60000,28,28,1)
x_test = x_test.reshape(10000,28,28,1)

In [7]:
from keras.utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [9]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
model = Sequential()
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

In [12]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3)

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 172s 3ms/step - loss: 0.2138 - accuracy: 0.9496 - val_loss: 0.0861 - val_accuracy: 0.9738
Epoch 2/3
60000/60000 [==============================] - 170s 3ms/step - loss: 0.0690 - accuracy: 0.9790 - val_loss: 0.0728 - val_accuracy: 0.9769
Epoch 3/3
60000/60000 [==============================] - 170s 3ms/step - loss: 0.0465 - accuracy: 0.9849 - val_loss: 0.0957 - val_accuracy: 0.9734


In [16]:
model.predict(x_test[:4])

array([[4.2337156e-09, 6.0035938e-15, 5.4477539e-08, 4.3357549e-08,
        2.1895376e-13, 2.9826995e-11, 3.9258397e-15, 9.9999988e-01,
        2.0031832e-09, 3.7554333e-08],
       [1.4751495e-08, 1.3892137e-10, 1.0000000e+00, 1.2365653e-11,
        7.9414345e-15, 1.1626701e-14, 4.4144365e-08, 1.5178248e-15,
        2.8155894e-11, 8.8833377e-15],
       [4.6719060e-07, 9.9968445e-01, 1.2596381e-04, 3.1643339e-07,
        1.3699541e-04, 1.9002426e-05, 2.4434619e-05, 1.0930104e-06,
        7.2818425e-06, 2.9210248e-08],
       [9.9999893e-01, 4.0282763e-14, 1.0726303e-06, 2.3422060e-13,
        1.5849716e-11, 7.6598519e-11, 1.1265397e-08, 5.0809912e-11,
        3.5360173e-08, 2.1111946e-08]], dtype=float32)

In [17]:
y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)